#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Repo-relative paths — run this script from the repo root.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUPABASE_PROJECT_REF="ubogyqskqzvkcqboqbhw"

# write_env_to TARGET_FILE KEY VALUE — write_env against a specific file
# instead of the global $ENV_FILE, without permanently changing it.
write_env_to() {
  local target="$1" key="$2" value="$3" saved="$ENV_FILE"
  ENV_FILE="$target"
  write_env "$key" "$value"
  ENV_FILE="$saved"
}

# set_supabase_secret NAME VALUE — set a Supabase Edge Function secret via the
# Supabase CLI (npx supabase). Logs in first if needed. Falls back to a
# recorded skip (with the manual command) if anything fails.
set_supabase_secret() {
  local name="$1" value="$2"
  if ! npx --yes supabase projects list >/dev/null 2>&1; then
    say "Not logged in to the Supabase CLI — this opens a browser login."
    npx --yes supabase login || true
  fi
  if npx --yes supabase secrets set "${name}=${value}" --project-ref "$SUPABASE_PROJECT_REF" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name (Supabase)")
    printf '  %s✓ set%s Supabase secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Supabase secret $name — run manually: npx supabase secrets set ${name}=<value> --project-ref $SUPABASE_PROJECT_REF")
    warn "skipped Supabase secret $name — set it manually later"
  fi
}

banner "UDine push notifications — VAPID + Firebase/FCM (Android only)"
say "Scope: Web Push (VAPID) for /web, and Android push via Expo + your own Firebase"
say "project (Google now requires this — the old legacy FCM server key is retired)."
say "iOS/APNs is out of scope for this pass."

# ── Stage 1: Web Push VAPID keypair ────────────────────────────────────────
stage "Web Push — VAPID keypair"
say "Generated locally — no dashboard needed, this is just key generation."
if ! command -v node >/dev/null 2>&1; then
  warn "node not found on PATH — install Node.js and re-run."
  exit 1
fi
VAPID_JSON="$(npx --yes web-push generate-vapid-keys --json 2>/dev/null)"
VAPID_PUBLIC_KEY="$(node -pe 'JSON.parse(process.argv[1]).publicKey' "$VAPID_JSON")"
VAPID_PRIVATE_KEY="$(node -pe 'JSON.parse(process.argv[1]).privateKey' "$VAPID_JSON")"
note "generated a public/private keypair"
ask VAPID_SUBJECT "Contact email for the VAPID subject (e.g. mailto:you@example.com):"
write_env_to "$REPO_ROOT/web/.env" "PUBLIC_VAPID_KEY" "$VAPID_PUBLIC_KEY"
set_supabase_secret "VAPID_PRIVATE_KEY" "$VAPID_PRIVATE_KEY"
set_supabase_secret "VAPID_SUBJECT" "$VAPID_SUBJECT"

# ── Stage 2: Link an EAS project to /mobile ────────────────────────────────
stage "Expo — link an EAS project"
say "This links mobile/ to an Expo Application Services project — needed to hold"
say "push credentials. Requires a free expo.dev account."
EXPO_USERNAME=""
if (cd "$REPO_ROOT/mobile" && npx --yes eas-cli whoami >/dev/null 2>&1); then
  EXPO_USERNAME="$(cd "$REPO_ROOT/mobile" && npx --yes eas-cli whoami 2>/dev/null | tail -1)" || true
  note "already logged in as $EXPO_USERNAME"
else
  say "Not logged in — this opens an interactive login."
  (cd "$REPO_ROOT/mobile" && npx --yes eas-cli login) || warn "login failed — you can retry with: npx eas-cli login (from mobile/)"
  EXPO_USERNAME="$(cd "$REPO_ROOT/mobile" && npx --yes eas-cli whoami 2>/dev/null | tail -1)" || true
fi
if confirm "Run 'eas init' now to link/create an EAS project for mobile/?"; then
  (cd "$REPO_ROOT/mobile" && npx --yes eas-cli init) || warn "eas init failed — retry later with: npx eas-cli init (from mobile/)"
else
  SKIPPED+=("eas init — run manually from mobile/: npx eas-cli init")
fi

# ── Stage 3: Firebase project + Android app registration ──────────────────
stage "Firebase — create project & register Android app"
say "Android package (already set in mobile/app.json): com.udinetogether.udine"
open_url "https://console.firebase.google.com/"
step "Create a new project (or reuse one) — its name doesn't need to match the app."
step "Add an app → Android → package name: com.udinetogether.udine"
step "Skip the SDK-setup code snippets (Expo handles that), but DO download google-services.json when offered."
ask FIREBASE_PROJECT_ID "Firebase project ID (Project Settings → General → 'Project ID'):"
pause "Downloaded google-services.json? Press Enter once you have it."
ask GOOGLE_SERVICES_JSON_PATH "Full path to the downloaded google-services.json:"
if [[ -f "$GOOGLE_SERVICES_JSON_PATH" ]]; then
  cp "$GOOGLE_SERVICES_JSON_PATH" "$REPO_ROOT/mobile/google-services.json"
  printf '  %s✓ copied%s to mobile/google-services.json\n' "$GREEN" "$RESET"
  note "follow-up (code, not this wizard): reference it via android.googleServicesFile in"
  note "mobile/app.json and install the expo-notifications plugin."
else
  warn "not found at that path — copy it to mobile/google-services.json manually."
  SKIPPED+=("mobile/google-services.json — copy manually from your download")
fi

# ── Stage 4: Firebase service account key (FCM V1, server-side) ───────────
stage "Firebase — service account key (FCM V1)"
say "This is the SERVER-side credential — different from google-services.json — that"
say "lets Expo's push servers send through your Firebase project."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/serviceaccounts/adminsdk"
step "Service Accounts tab → 'Generate new private key' → confirm the download."
pause "Downloaded the service account JSON? Press Enter once you have it."
ask FIREBASE_SERVICE_ACCOUNT_PATH "Full path to the downloaded service account JSON:"
if [[ ! -f "$FIREBASE_SERVICE_ACCOUNT_PATH" ]]; then
  warn "not found — you'll need it for the next stage; re-run this wizard once you have it."
  SKIPPED+=("Firebase service account JSON — needed for the EAS credentials upload in stage 5")
fi

# ── Stage 5: Upload the service account to EAS ─────────────────────────────
stage "EAS — upload FCM V1 credentials"
say "This tells Expo's push service how to deliver to your Firebase project."
if [[ -f "${FIREBASE_SERVICE_ACCOUNT_PATH:-}" ]]; then
  say "About to run: eas credentials (interactive). When prompted, pick:"
  step "Android → your app → Push Notifications → Manage FCM V1 credentials → Upload a service account key"
  note "point it at: $FIREBASE_SERVICE_ACCOUNT_PATH"
  pause "Press Enter to launch eas credentials…"
  (cd "$REPO_ROOT/mobile" && npx --yes eas-cli credentials) || warn "exited — re-run 'npx eas-cli credentials' from mobile/ any time."
else
  warn "no service account JSON path captured — run 'npx eas-cli credentials' manually from mobile/ once you have it."
  SKIPPED+=("EAS FCM V1 credential upload — run: npx eas-cli credentials (from mobile/)")
fi

# ── Stage 6: Expo access token → Supabase secret ───────────────────────────
stage "Expo access token → Supabase secret"
say "Lets the check-favorited-foods Edge Function call Expo's push API on your behalf."
if [[ -n "$EXPO_USERNAME" ]]; then
  open_url "https://expo.dev/accounts/${EXPO_USERNAME}/settings/access-tokens"
else
  open_url "https://expo.dev/"
  note "navigate to: your account → Settings → Access Tokens"
fi
step "Create token → name it (e.g. 'udine-edge-function') → copy the value now (shown once)."
ask_secret EXPO_ACCESS_TOKEN_VALUE "Paste the Expo access token:"
set_supabase_secret "EXPO_ACCESS_TOKEN" "$EXPO_ACCESS_TOKEN_VALUE"

finish
note "Not covered here (separate implementation work, not credentials):"
note "  - installing expo-notifications and wiring android.googleServicesFile in mobile/app.json"
note "  - client-side push-token registration (writing to the push_tokens table)"
note "  - the actual push-send code in check-favorited-foods/index.ts"
note "  - the pg_cron job that invokes check-favorited-foods (deferred per docs/adr/0002 until this script's secrets exist)"
