import type { CustomFood } from "@udine/shared";

/**
 * Raw text-field values off CustomFoodForm.tsx's manual-entry form -- the 4 core macros are
 * required up front (canvas spec), everything else lives behind a "More nutrition fields"
 * expandable section and stays optional. Pure builder pulled out of the component so the
 * required/optional split and the numeric-field defaulting are testable without rendering.
 */
export interface CustomFoodFormInput {
  name: string;
  servingSize: string;
  calories: string;
  proteinG: string;
  totalCarbG: string;
  totalFatG: string;
  caloriesFromFat?: string;
  satFatG?: string;
  transFatG?: string;
  cholesterolMg?: string;
  sodiumMg?: string;
  dietaryFiberG?: string;
  sugarsG?: string;
  ingredients?: string;
}

/** Blank/non-numeric text-field input defaults to 0 rather than NaN -- a quick entry that only
 * fills the 4 required macros must not silently ship NaN into every unset NutritionFacts field
 * (the log/macro-totals math downstream has no NaN guards of its own). This is a mapping
 * primitive only, NOT the "are the core macros filled in" check -- see hasRequiredCoreMacros
 * below, which the form gates Save on so this fallback is never actually reachable for a core
 * field from the UI. */
function num(value: string | undefined): number {
  const n = Number(value);
  return value !== undefined && value.trim() !== "" && Number.isFinite(n) ? n : 0;
}

const CORE_MACRO_FIELDS = ["calories", "proteinG", "totalCarbG", "totalFatG"] as const;

/** The "4 core macros required up front" contract (canvas spec, this file's own doc above) --
 * CustomFoodForm.tsx gates its Save button on this so a blank/non-numeric core field can never
 * reach buildCustomFood's silent num()->0 fallback (that fallback exists for the truly-optional
 * "more nutrition fields" section, not these). */
export function hasRequiredCoreMacros(input: Pick<CustomFoodFormInput, (typeof CORE_MACRO_FIELDS)[number]>): boolean {
  return CORE_MACRO_FIELDS.every((field) => {
    const trimmed = input[field].trim();
    return trimmed !== "" && Number.isFinite(Number(trimmed));
  });
}

/** Builds a CustomFood from form input, or null when the one truly required field (name) is
 * blank -- the caller (CustomFoodForm.tsx) is expected to block Save on a null return rather than
 * this throwing. `id` is generated by the caller (matches plate.ts's toLogEntries's own
 * Math.random().toString(36) id convention) so this stays a pure, easily-testable mapping. */
export function buildCustomFood(input: CustomFoodFormInput, id: string): CustomFood | null {
  const name = input.name.trim();
  if (!name) return null;
  const servingSize = input.servingSize.trim() || "1 serving";
  const nutrition = {
    servingSize,
    calories: num(input.calories),
    caloriesFromFat: num(input.caloriesFromFat),
    totalFatG: num(input.totalFatG),
    satFatG: num(input.satFatG),
    transFatG: num(input.transFatG),
    cholesterolMg: num(input.cholesterolMg),
    sodiumMg: num(input.sodiumMg),
    totalCarbG: num(input.totalCarbG),
    dietaryFiberG: num(input.dietaryFiberG),
    sugarsG: num(input.sugarsG),
    proteinG: num(input.proteinG),
  };
  const ingredients = input.ingredients?.trim();
  return { id, name, servingSize, nutrition, ...(ingredients ? { ingredients } : {}) };
}
